// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: hoepperCount.sql

package db

import (
	"context"
)

const startHoepperCount = `-- name: StartHoepperCount :one
INSERT INTO "hoepperCount" (
    hoepper, victim, count
) VALUES (
    $1, $2, 1
) RETURNING hoepper, victim, "hoepperCount"
`

type StartHoepperCountParams struct {
	Hoepper int64 `json:"hoepper"`
	Victim  int64 `json:"victim"`
}

func (q *Queries) StartHoepperCount(ctx context.Context, arg StartHoepperCountParams) (HoepperCount, error) {
	row := q.db.QueryRowContext(ctx, startHoepperCount, arg.Hoepper, arg.Victim)
	var i HoepperCount
	err := row.Scan(&i.Hoepper, &i.Victim, &i.HoepperCount)
	return i, err
}
